[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "cof-fl-1001-no1"
version = "1.0.0"
description = "Federated learning for CoF prediction - 1001_no1"
requires-python = ">=3.10"

dependencies = [
    "flwr[simulation]>=1.31.0",
    "torch",
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
]


[tool.flwr.app]
publisher = "shiyu"


[tool.flwr.app.components]
serverapp = "server_app:app"
clientapp = "client_app:app"


[tool.flwr.app.config]

# Experiment
seed = 42
num-clients = 2

# Federated Learning
num-server-rounds = 60
local-epochs = 10
batch-size = 7
learning-rate = 0.001

# Client participation
fraction-train = 1.0

# Preprocessing
standardization = "zscore"

# Data
data-dir = "/home/shiyu/fl_test/1001_no1/data/splits"
test-data-path = "/home/shiyu/fl_test/1001_no1/data/splits/test.csv"


[tool.flwr.federations]
default = "local-simulation"


[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
